apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: demo2
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
        - name: demo2
          image: mykubernetes2345registry.azurecr.io/demo2_image:v1
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 250m
            limits:
              cpu: 500m
          env:
            - name: REDIS
              value: "demo2"
---
apiVersion: v1
kind: Service
metadata:
  name: demo2
spec:
  type: LoadBalancer
  ports:
    - port: 8080
  selector:
    app: demo2
