version: '3'

networks:
  mynetwork:
    driver: bridge

services:

  minimal:
    container_name: minimal
    image: minimal:latest
    ports:
      - 8080:8080
    environment:
      - TEST=value
    networks:
      - mynetwork